// Fails when src/web/wasm was built from a different crates/ tree than the one on disk,
// or when wasm-pack's generated .gitignore is still present. Needs git, not Rust.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { buildJsonPath, cratesTreeHash, outDir, outName } from "./wasm-build.mjs";

const problems = [];

if (!existsSync(buildJsonPath)) {
  problems.push("wasm/BUILD.json is missing; run `npm run wasm:build`.");
} else {
  const build = JSON.parse(readFileSync(buildJsonPath, "utf8"));
  const expected = cratesTreeHash();
  if (build.cratesTreeHash !== expected) {
    problems.push(
      `wasm/ was built from crates tree ${build.cratesTreeHash}, the working tree is ${expected}; run \`npm run wasm:build\` and commit src/web/wasm/.`,
    );
  }
}

for (const file of [`${outName}.js`, `${outName}.d.ts`, `${outName}_bg.wasm`]) {
  if (!existsSync(join(outDir, file))) problems.push(`wasm/${file} is missing.`);
}
if (existsSync(join(outDir, ".gitignore"))) {
  problems.push("wasm/.gitignore (generated by wasm-pack) would un-commit the artifact; delete it.");
}

if (problems.length > 0) {
  for (const p of problems) console.error(`wasm:check: ${p}`);
  process.exit(1);
}
console.log("wasm:check: wasm/ matches the crates tree on disk.");
